export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED'

export const ADD_TASK_START = 'ADD_TASK_START'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED'

export const DELETE_TASK_START = 'DELETE_TASK_START'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED'
export const DELETE_TASK_ALERT = 'DELETE_TASK_ALERT'

export const EDIT_TASK_INIT = 'EDIT_TASK_INIT'
export const EDIT_TASK_START = 'EDIT_TASK_START'
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
export const EDIT_TASK_FAILED = 'EDIT_TASK_FAILED'

export const COMPLETED_TASK_START = 'COMPLETED_TASK_START'
export const COMPLETED_TASK_SUCCESS = 'COMPLETED_TASK_SUCCESS'
export const COMPLETED_TASK_FAILED = 'COMPLETED_TASK_FAILED'

export const SEARCH_TASK_SUCCESS = 'SEARCH_TASK_SUCCESS'
export const SEARCH_TASK_FAILED = 'SEARCH_TASK_FAILED'

export const MODAL_SHOW = 'MODAL_SHOW'
export const MODAL_CLOSE = 'MODAL_CLOSE'

export const SET_TITLE = 'SET_TITLE'
export const SET_DESCRIPTION = 'SET_DESCRIPTION'
export const SET_EDIT_TITLE = 'SET_EDIT_TITLE'
export const SET_EDIT_DESCRIPTION = 'SET_EDIT_DESCRIPTION'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'